// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/bc": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/bc";
  };
  "./app.tsx": {
    id: "app";
    page: "/";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/bc.tsx": {
    id: "routes/bc";
    page: "/bc";
  };
};